services:
  mock-modbus-server:
    container_name: modbus-server
    image: oitc/modbus-server:latest
    restart: always
    command: -f /server_config.json
    ports:
      - 5020:1503
    volumes:
      - ./server.json:/server_config.json:ro
  influxdb:
    image: influxdb:latest
    volumes:
      # Mount for influxdb data directory and configuration
      - ./influxdb:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    restart: unless-stopped
